//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class CommunitiesView
    {
        public long CommunityID { get; set; }
        public string CommunityName { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string DistributedBy { get; set; }
        public Nullable<System.Guid> ThumbnailID { get; set; }
        public long CreatedByID { get; set; }
        public int CommunityTypeID { get; set; }
        public string ProducedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDatetime { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string ParentName { get; set; }
        public string AccessType { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public Nullable<int> RatedPeople { get; set; }
        public string Tags { get; set; }
        public Nullable<long> ViewCount { get; set; }
    }
}
