//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class CommunityRatings
    {
        public long CommunityRatingsID { get; set; }
        public long CommunityID { get; set; }
        public decimal Rating { get; set; }
        public Nullable<long> RatedByID { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
    
        public virtual User User { get; set; }
        public virtual Community Community { get; set; }
    }
}
