//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class ContentComments
    {
        public ContentComments()
        {
            this.ContentComments1 = new HashSet<ContentComments>();
        }
    
        public long ContentCommentsID { get; set; }
        public long ContentID { get; set; }
        public string Comment { get; set; }
        public Nullable<long> CommentedByID { get; set; }
        public Nullable<System.DateTime> CommentDatetime { get; set; }
        public Nullable<long> ReplyCommentID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<ContentComments> ContentComments1 { get; set; }
        public virtual ContentComments ContentComments2 { get; set; }
        public virtual User User { get; set; }
        public virtual Content Content { get; set; }
    }
}
