//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class InviteRequestsView
    {
        public int InviteRequestID { get; set; }
        public System.Guid InviteRequestToken { get; set; }
        public string EmailID { get; set; }
        public int RoleID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string InvitedBy { get; set; }
        public Nullable<System.DateTime> InvitedDate { get; set; }
        public long CommunityID { get; set; }
        public string CommunityName { get; set; }
        public Nullable<bool> Used { get; set; }
    }
}
