//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class OffensiveContent
    {
        public long OffensiveContentID { get; set; }
        public int OffensiveStatusID { get; set; }
        public long ContentID { get; set; }
        public long ReportedByID { get; set; }
        public System.DateTime ReportedDatetime { get; set; }
        public string Justification { get; set; }
        public Nullable<long> ReviewerID { get; set; }
        public Nullable<System.DateTime> ReviewerDatetime { get; set; }
        public string Comments { get; set; }
        public int OffensiveTypeID { get; set; }
    
        public virtual OffenceType OffenceType { get; set; }
        public virtual OffensiveStatus OffensiveStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Content Content { get; set; }
    }
}
