//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class TopCategoryEntities
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string Filename { get; set; }
        public Nullable<int> TypeID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<System.Guid> ThumbnailID { get; set; }
        public Nullable<long> CommunityID { get; set; }
        public string CommunityName { get; set; }
        public string Tags { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public Nullable<int> RatedPeople { get; set; }
        public Nullable<int> CommunityTypeID { get; set; }
        public string EntityType { get; set; }
    }
}
