//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class CommunityComments
    {
        public CommunityComments()
        {
            this.CommunityComments1 = new HashSet<CommunityComments>();
        }
    
        public long CommunityCommentsID { get; set; }
        public long CommunityID { get; set; }
        public string Comment { get; set; }
        public long CommentedByID { get; set; }
        public System.DateTime CommentedDatetime { get; set; }
        public Nullable<long> ReplyCommentID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<CommunityComments> CommunityComments1 { get; set; }
        public virtual CommunityComments CommunityComments2 { get; set; }
        public virtual User User { get; set; }
        public virtual Community Community { get; set; }
    }
}
