//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class Content
    {
        public Content()
        {
            this.CommunityContents = new HashSet<CommunityContents>();
            this.ContentComments = new HashSet<ContentComments>();
            this.ContentRatings = new HashSet<ContentRatings>();
            this.ContentRelation = new HashSet<ContentRelation>();
            this.ContentRelation1 = new HashSet<ContentRelation>();
            this.ContentTags = new HashSet<ContentTags>();
            this.OffensiveContent = new HashSet<OffensiveContent>();
            this.FeaturedContents = new HashSet<FeaturedContents>();
        }
    
        public long ContentID { get; set; }
        public int TypeID { get; set; }
        public string Title { get; set; }
        public string Filename { get; set; }
        public string Description { get; set; }
        public System.Guid ContentAzureID { get; set; }
        public string ContentAzureURL { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<int> DownloadCount { get; set; }
        public Nullable<int> AccessTypeID { get; set; }
        public Nullable<System.Guid> ThumbnailID { get; set; }
        public bool IsSearchable { get; set; }
        public Nullable<bool> IsOffensive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<long> ModifiedByID { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public Nullable<long> DeletedByID { get; set; }
        public Nullable<System.DateTime> DeletedDatetime { get; set; }
        public int CategoryID { get; set; }
        public string DistributedBy { get; set; }
        public string Citation { get; set; }
        public string ContentUrl { get; set; }
        public string TourRunLength { get; set; }
    
        public virtual AccessType AccessType { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<CommunityContents> CommunityContents { get; set; }
        public virtual ICollection<ContentComments> ContentComments { get; set; }
        public virtual ICollection<ContentRatings> ContentRatings { get; set; }
        public virtual ICollection<ContentRelation> ContentRelation { get; set; }
        public virtual ICollection<ContentRelation> ContentRelation1 { get; set; }
        public virtual ICollection<ContentTags> ContentTags { get; set; }
        public virtual ICollection<OffensiveContent> OffensiveContent { get; set; }
        public virtual ContentType ContentType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<FeaturedContents> FeaturedContents { get; set; }
    }
}
