//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class EarthOnlineEntities : DbContext
    {
        public EarthOnlineEntities()
            : base("name=EarthOnlineEntities")
        {
        }
    
        public EarthOnlineEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessType> AccessType { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<CommunityComments> CommunityComments { get; set; }
        public DbSet<CommunityContents> CommunityContents { get; set; }
        public DbSet<CommunityRatings> CommunityRatings { get; set; }
        public DbSet<CommunityRelation> CommunityRelation { get; set; }
        public DbSet<CommunityTags> CommunityTags { get; set; }
        public DbSet<ContentComments> ContentComments { get; set; }
        public DbSet<ContentRatings> ContentRatings { get; set; }
        public DbSet<ContentRelation> ContentRelation { get; set; }
        public DbSet<ContentRelationshipType> ContentRelationshipType { get; set; }
        public DbSet<ContentTags> ContentTags { get; set; }
        public DbSet<ContentType> ContentType { get; set; }
        public DbSet<OffenceType> OffenceType { get; set; }
        public DbSet<OffensiveCommunities> OffensiveCommunities { get; set; }
        public DbSet<OffensiveContent> OffensiveContent { get; set; }
        public DbSet<OffensiveStatus> OffensiveStatus { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Tag> Tag { get; set; }
        public DbSet<UserCommunities> UserCommunities { get; set; }
        public DbSet<UserType> UserType { get; set; }
        public DbSet<CommunityType> CommunityType { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Community> Community { get; set; }
        public DbSet<Content> Content { get; set; }
        public DbSet<CommunitiesView> CommunitiesView { get; set; }
        public DbSet<ContentsView> ContentsView { get; set; }
        public DbSet<PermissionRequest> PermissionRequest { get; set; }
        public DbSet<InviteRequestContent> InviteRequestContent { get; set; }
        public DbSet<InviteRequest> InviteRequest { get; set; }
        public DbSet<InviteRequestsView> InviteRequestsView { get; set; }
        public DbSet<StaticContent> StaticContent { get; set; }
        public DbSet<StaticContentType> StaticContentType { get; set; }
        public DbSet<FeaturedCommunities> FeaturedCommunities { get; set; }
        public DbSet<FeaturedContents> FeaturedContents { get; set; }
        public DbSet<FeaturedCommunitiesView> FeaturedCommunitiesView { get; set; }
        public DbSet<FeaturedContentsView> FeaturedContentsView { get; set; }
        public DbSet<SearchView> SearchView { get; set; }
        public DbSet<AllCommunitiesView> AllCommunitiesView { get; set; }
        public DbSet<AllContentsView> AllContentsView { get; set; }
        public DbSet<TopCategoryEntities> TopCategoryEntities { get; set; }
    }
}
