//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class FeaturedContents
    {
        public long FeaturedContentsID { get; set; }
        public long ContentID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<long> UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Content Content { get; set; }
        public virtual User User { get; set; }
    }
}
