//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class InviteRequest
    {
        public int InviteRequestID { get; set; }
        public System.Guid InviteRequestToken { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<long> UsedByID { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeletedByID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int InviteRequestContentID { get; set; }
    
        public virtual InviteRequestContent InviteRequestContent { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
