//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class PermissionRequest
    {
        public int PermissionRequestID { get; set; }
        public long UserID { get; set; }
        public long CommunityID { get; set; }
        public int RoleID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<long> RespondedByID { get; set; }
        public Nullable<System.DateTime> RespondedDate { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
