//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class Role
    {
        public Role()
        {
            this.UserCommunities = new HashSet<UserCommunities>();
            this.PermissionRequest = new HashSet<PermissionRequest>();
            this.InviteRequestContent = new HashSet<InviteRequestContent>();
        }
    
        public int RoleID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<UserCommunities> UserCommunities { get; set; }
        public virtual ICollection<PermissionRequest> PermissionRequest { get; set; }
        public virtual ICollection<InviteRequestContent> InviteRequestContent { get; set; }
    }
}
