//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWTMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EdmxTool", "1.0.0.0")] 
    public partial class User
    {
        public User()
        {
            this.CommunityComments = new HashSet<CommunityComments>();
            this.CommunityRatings = new HashSet<CommunityRatings>();
            this.CommunityTags = new HashSet<CommunityTags>();
            this.ContentComments = new HashSet<ContentComments>();
            this.ContentRatings = new HashSet<ContentRatings>();
            this.ContentTags = new HashSet<ContentTags>();
            this.OffensiveCommunities = new HashSet<OffensiveCommunities>();
            this.OffensiveCommunities1 = new HashSet<OffensiveCommunities>();
            this.OffensiveContent = new HashSet<OffensiveContent>();
            this.OffensiveContent1 = new HashSet<OffensiveContent>();
            this.User1 = new HashSet<User>();
            this.UserCommunities = new HashSet<UserCommunities>();
            this.Community = new HashSet<Community>();
            this.Community1 = new HashSet<Community>();
            this.Community2 = new HashSet<Community>();
            this.Content = new HashSet<Content>();
            this.Content1 = new HashSet<Content>();
            this.Content2 = new HashSet<Content>();
            this.PermissionRequest = new HashSet<PermissionRequest>();
            this.PermissionRequest1 = new HashSet<PermissionRequest>();
            this.InviteRequestContent = new HashSet<InviteRequestContent>();
            this.InviteRequest = new HashSet<InviteRequest>();
            this.InviteRequest1 = new HashSet<InviteRequest>();
            this.StaticContent = new HashSet<StaticContent>();
            this.StaticContent1 = new HashSet<StaticContent>();
            this.StaticContent2 = new HashSet<StaticContent>();
            this.FeaturedCommunities = new HashSet<FeaturedCommunities>();
            this.FeaturedContents = new HashSet<FeaturedContents>();
        }
    
        public long UserID { get; set; }
        public string Email { get; set; }
        public string LiveID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> LastLoginDatetime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeletedByID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<decimal> ConsumedSize { get; set; }
        public string Affiliation { get; set; }
        public string AboutMe { get; set; }
        public bool IsSubscribed { get; set; }
        public Nullable<System.Guid> PictureID { get; set; }
        public Nullable<System.DateTime> JoinedDateTime { get; set; }
    
        public virtual ICollection<CommunityComments> CommunityComments { get; set; }
        public virtual ICollection<CommunityRatings> CommunityRatings { get; set; }
        public virtual ICollection<CommunityTags> CommunityTags { get; set; }
        public virtual ICollection<ContentComments> ContentComments { get; set; }
        public virtual ICollection<ContentRatings> ContentRatings { get; set; }
        public virtual ICollection<ContentTags> ContentTags { get; set; }
        public virtual ICollection<OffensiveCommunities> OffensiveCommunities { get; set; }
        public virtual ICollection<OffensiveCommunities> OffensiveCommunities1 { get; set; }
        public virtual ICollection<OffensiveContent> OffensiveContent { get; set; }
        public virtual ICollection<OffensiveContent> OffensiveContent1 { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<UserCommunities> UserCommunities { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Community> Community { get; set; }
        public virtual ICollection<Community> Community1 { get; set; }
        public virtual ICollection<Community> Community2 { get; set; }
        public virtual ICollection<Content> Content { get; set; }
        public virtual ICollection<Content> Content1 { get; set; }
        public virtual ICollection<Content> Content2 { get; set; }
        public virtual ICollection<PermissionRequest> PermissionRequest { get; set; }
        public virtual ICollection<PermissionRequest> PermissionRequest1 { get; set; }
        public virtual ICollection<InviteRequestContent> InviteRequestContent { get; set; }
        public virtual ICollection<InviteRequest> InviteRequest { get; set; }
        public virtual ICollection<InviteRequest> InviteRequest1 { get; set; }
        public virtual ICollection<StaticContent> StaticContent { get; set; }
        public virtual ICollection<StaticContent> StaticContent1 { get; set; }
        public virtual ICollection<StaticContent> StaticContent2 { get; set; }
        public virtual ICollection<FeaturedCommunities> FeaturedCommunities { get; set; }
        public virtual ICollection<FeaturedContents> FeaturedContents { get; set; }
    }
}
